### ISSUE TITLE
動かない

### ISSUE THREAD

**Issue by mmxsrup** [kmyk/online-judge-tools#1]
```
% oj download http://yukicoder.me/problems/no/475                                [~/Documents/yukicoder/400/475]+[master]
[+] problem recognized: <onlinejudge.yukicoder.Yukicoder object at 0x102c01240>
[x] GET: https://yukicoder.me/problems/no/475
[x] 200 OK
Traceback (most recent call last):
  File "/Users/yuichi/Downloads/online-judge-tools/main.py", line 165, in <module>
    main()
  File "/Users/yuichi/Downloads/online-judge-tools/main.py", line 154, in main
    download(args)
  File "/Users/yuichi/Downloads/online-judge-tools/main.py", line 52, in download
    samples = problem.download(session=sess, **kwargs)
  File "/Users/yuichi/Downloads/online-judge-tools/onlinejudge/yukicoder.py", line 28, in download
    return self.download_samples(session=session)
  File "/Users/yuichi/Downloads/online-judge-tools/onlinejudge/yukicoder.py", line 31, in download_samples
    soup = bs4.BeautifulSoup(content, 'lxml')
  File "/usr/local/lib/python3.5/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by kmyk** [comment]
たぶん直った

**Comment by kmyk** [comment]
BeautifulSoupの設定を変えた たぶん直った

**Comment by mmxsrup** [comment]
mac OS X で動くようになりました

**Comment by kmyk** [comment]
:smile:
