### ISSUE TITLE
pip3でのインストールがうまくいかない

### ISSUE THREAD

**Issue by btk15049** [kmyk/online-judge-tools#101]
文字コード関連のエラーっぽいのが出てpip3でのインストールが上手くできないです．

```
$ pip3 install online-judge-tools
Collecting online-judge-tools
  Using cached online-judge-tools-0.1.26.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Y\AppData\Local\Temp\pip-build-r09u57ot\online-judge-tools\setup.py", line 14, in <module>
        readme = fh.read()
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x8b in position 2101: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Y\AppData\Local\Temp\pip-build-r09u57ot\online-judge-tools\
```

**Comment by kmyk** [comment]
:+1:

UTF8のファイルを開こうとして「SHIFT_JISじゃねえ :anger:」って死んでるように見える
指定してやれば直りそう

**Comment by kmyk** [comment]
修正してpypiにuploadしました。その部分については解決したはず
確認お願いします

**Comment by kmyk** [comment]
直ったぽい
