### ISSUE TITLE
pip3 install online-judge-toolsでいれたらエラーがでます.

### ISSUE THREAD

**Issue by mmxsrup** [kmyk/online-judge-tools#11]
```sh
% oj download http://agc001.contest.atcoder.jp/tasks/agc001_a                                                    [~]+[master]
Traceback (most recent call last):
  File "/usr/local/bin/oj", line 2, in <module>
    import onlinejudge.implementation.main
  File "/usr/local/lib/python3.5/site-packages/onlinejudge/implementation/main.py", line 6, in <module>
    from onlinejudge.implementation.command.download import download
ImportError: No module named 'onlinejudge.implementation.command'
```
環境はmacOSX です.

**Comment by kmyk** [comment]
ありがとう
なんだかこちらのコーディングミスに見えるしわりとやばそう 今日中に修正します

**Comment by kmyk** [comment]
修正できたはず
directoryを切ったのに__init__.pyを作るの忘れていて中身が配布対象に含まれてなかったぽい

**Comment by mmxsrup** [comment]
```sh
% pip3 uninstall online-judge-tools
% pip3 install online-judge-tools
```
uninstall後にinstallしたら、動くようになりました.

**Comment by kmyk** [comment]
:smile:
