### ISSUE TITLE
Yukicoder No. 3016, 成功してもよさそうなgenerate-scannerの失敗

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#12]
```
$ oj g/s http://yukicoder.me/problems/no/3016                                                                                                                                            ~contest/yuki/3016
[!] This feature is experimental.
[x] problem recognized: <onlinejudge.yukicoder.YukicoderProblem object at 0x7f4a553c12b0>: http://yukicoder.me/problems/no/3016
[*] load cookie from: /home/user/.local/share/onlinejudge/cookie.jar
[x] GET: https://yukicoder.me/problems/no/3016
[x] 200 OK
[*] save cookie to: /home/user/.local/share/onlinejudge/cookie.jar
[ERROR] somethin wrong
Traceback (most recent call last):
  File "/usr/local/bin/oj", line 6, in <module>
    onlinejudge.implementation.main.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/onlinejudge/implementation/main.py", line 273, in main
    generate_scanner(args)
  File "/usr/local/lib/python3.5/dist-packages/onlinejudge/implementation/command/generate_scanner.py", line 182, in generate_scanner
    it = tokenize(it)
  File "/usr/local/lib/python3.5/dist-packages/onlinejudge/implementation/command/generate_scanner.py", line 25, in tokenize
    assert False
AssertionError
```

**Comment by kmyk** [comment]
http://yukicoder.me/problems/no/483

**Comment by kmyk** [comment]
よく見たらこれは無理
