### ISSUE TITLE
CIが壊れてるので直す

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#147]
https://github.com/kmyk/online-judge-tools/pull/146 でデグレ
なぜか突然pathが通らなくなったぽい？ 動くはずなので押し切ってしまったが (最悪)

さらにhackerrankがsample dlにloginを要求してくるようになったぽいので対処
定期のやつがやられてた: https://travis-ci.org/kmyk/online-judge-tools/builds/355239183

**Comment by kmyk** [comment]
https://travis-ci.org/kmyk/online-judge-tools/builds/354445911
`import onlinejudge.implementation.utils as utils` って書いて `AttributeError: module 'onlinejudge' has no attribute 'implementation'` ってなんだよ

``` python
$ python setup.py test
running test
running egg_info
creating online_judge_tools.egg-info
writing dependency_links to online_judge_tools.egg-info/dependency_links.txt
writing requirements to online_judge_tools.egg-info/requires.txt
writing top-level names to online_judge_tools.egg-info/top_level.txt
writing online_judge_tools.egg-info/PKG-INFO
writing manifest file 'online_judge_tools.egg-info/SOURCES.txt'
reading manifest file 'online_judge_tools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'online_judge_tools.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    'Topic :: Utilities',
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/3.5.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.5.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.5.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/opt/python/3.5.5/lib/python3.5/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/opt/python/3.5.5/lib/python3.5/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/opt/python/3.5.5/lib/python3.5/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/opt/python/3.5.5/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/opt/python/3.5.5/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/opt/python/3.5.5/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/opt/python/3.5.5/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/travis/build/kmyk/online-judge-tools/tests/code_statistics.py", line 3, in <module>
    from onlinejudge.implementation.command.code_statistics import get_statistics
  File "/home/travis/build/kmyk/online-judge-tools/onlinejudge/__init__.py", line 10, in <module>
    import onlinejudge.topcoder
  File "/home/travis/build/kmyk/online-judge-tools/onlinejudge/topcoder.py", line 6, in <module>
    import onlinejudge.implementation.utils as utils
AttributeError: module 'onlinejudge' has no attribute 'implementation'
```

**Comment by kmyk** [comment]
原因これだった あのerrmsgで分かる訳がないだろいい加減にしろ
https://github.com/kmyk/online-judge-tools/blob/de828fa1b8b789ac34cd08d3da77a6794779635a/onlinejudge/topcoder.py#L14

**Comment by kmyk** [comment]
#147 の参照のせいで苦労の跡が分かりやすい

**Comment by kmyk** [comment]
:tada:
