### ISSUE TITLE
yukicoder No.104 国道 で正常に動きません

### ISSUE THREAD

**Issue by mmxsrup** [kmyk/online-judge-tools#2]
```
% oj download http://yukicoder.me/problems/no/104                                [~/Documents/yukicoder/100/104]+[master]
[x] problem recognized: <onlinejudge.yukicoder.YukicoderProblem object at 0x1072ac588>: http://yukicoder.me/problems/no/104
[*] load cookie from: /Users/yuichi/local/share/onlinejudge/cookie.jar
[x] GET: https://yukicoder.me/problems/no/104
[x] 200 OK
Traceback (most recent call last):
  File "/Users/yuichi/Programs/online-judge-tools/main.py", line 151, in <module>
    main()
  File "/Users/yuichi/Programs/online-judge-tools/main.py", line 140, in main
    download(args)
  File "/Users/yuichi/Programs/online-judge-tools/main.py", line 34, in download
    samples = problem.download(session=sess, **kwargs)
  File "/Users/yuichi/Programs/online-judge-tools/onlinejudge/yukicoder.py", line 91, in download
    return self.download_samples(session=session)
  File "/Users/yuichi/Programs/online-judge-tools/onlinejudge/yukicoder.py", line 105, in download_samples
    it = self._parse_sample_tag(pre)
  File "/Users/yuichi/Programs/online-judge-tools/onlinejudge/yukicoder.py", line 138, in _parse_sample_tag
    return utils.textfile(tag.string.lstrip()), pprv.string + ' ' + prv.string
AttributeError: 'NoneType' object has no attribute 'lstrip'
```

**Comment by kmyk** [comment]
報告ありがとう 修正します

**Comment by kmyk** [comment]
修正しました
間に空白も存在しない `<pre></pre>` があると落ちるようだった
