### ISSUE TITLE
AtCoder への提出に失敗する

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#23]
デグレっぽい

```
[*] load cookie from: /home/user/.local/share/onlinejudge/cookie.jar
[x] GET: http://agc014.contest.atcoder.jp/submit
[x] 200 OK
[x] sleep(3.00)
[x] GET: http://agc014.contest.atcoder.jp/submit
[x] 200 OK
[x] GET: http://agc014.contest.atcoder.jp/submit
[x] 200 OK
[x] GET: http://agc014.contest.atcoder.jp/tasks/agc014_e
[x] 200 OK
[x] POST: https://agc014.contest.atcoder.jp/submit?task_id=2373
[x] 200 OK
[+] success: result: https://agc014.contest.atcoder.jp/submissions/me#30393
Traceback (most recent call last):
  File "/usr/local/bin/oj", line 6, in <module>
    onlinejudge.implementation.main.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/onlinejudge/implementation/main.py", line 267, in main
    submit(args)
  File "/usr/local/lib/python3.5/dist-packages/onlinejudge/implementation/command/submit.py", line 48, in submit
    submission = problem.submit(code, language=args.language, session=sess)
  File "/usr/local/lib/python3.5/dist-packages/onlinejudge/atcoder.py", line 234, in submit
    return AtCoderSubmission.from_url(resp.url, problem_id=self.problem_id)
TypeError: from_url() got an unexpected keyword argument 'problem_id'
```

**Comment by kmyk** [comment]
失敗するというより、提出成功にこける
