### ISSUE TITLE
test: '+'などを含むディレクトリでregexpがエラーを吐く

### ISSUE THREAD

**Issue by Pachicobue** [kmyk/online-judge-tools#256]
## 発生した問題
ディレクトリ名に'+'などを含む場合にtestコマンドが失敗します

```
Traceback (most recent call last):
  File "./online-judge-tools/oj", line 6, in <module>
    onlinejudge.implementation.main.main(args=sys.argv[1:])
  File "/home/sho/Programming/C++/online-judge-tools/onlinejudge/implementation/main.py", line 349, in main
    run_program(namespace, parser=parser)
  File "/home/sho/Programming/C++/online-judge-tools/onlinejudge/implementation/main.py", line 324, in run_program
    test(args)
  File "/home/sho/Programming/C++/online-judge-tools/onlinejudge/implementation/command/test.py", line 42, in test
    tests = cutils.construct_relationship_of_files(args.test, args.directory, args.format)
  File "/home/sho/Programming/C++/online-judge-tools/onlinejudge/implementation/format_utils.py", line 51, in construct_relationship_of_files
    m = match_with_format(directory, format, path.resolve())
  File "/home/sho/Programming/C++/online-judge-tools/onlinejudge/implementation/format_utils.py", line 26, in match_with_format
    pattern = re.compile('^' + str(directory.resolve()) + '/' + utils.percentformat(format, table) + '$')
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 654, in _parse
    source.tell() - here + len(this))
re.error: multiple repeat at position 25
```

## 再現方法
```shell-script
$ cd ~/C++
$ oj dl https://atcoder.jp/contests/abs/tasks/abc086_a
$ g++ main.cpp 
$ oj test
```

## 解決方法(?)
`onlinejudge/implementation/format_utils.py`の`match_with_format`関数で

``` python
pattern = re.compile('^' + str(directory.resolve()) + '/' + utils.percentformat(format, table) + '$')
```

を
```python
pattern = re.compile('^' + re.escape(str(directory.resolve())) + '/' + utils.percentformat(format, table) + '$')
```
とエスケープすれば上のケースでは上手く行きます。  
本当は他にもエスケープするべき箇所があるかもしれません。

**Comment by kmyk** [comment]
報告ありがとうございます。バグなので直します。

**Comment by fukatani** [comment]
`re.escape(str(directory.resolve()) + '/' + utils.percentformat(format, table))`
がいいかもしれません。

**Comment by kmyk** [comment]
`utils.percentformat(format, table)` もエスケープするべきというの正しそう。
しかし丸ごとやるとよくない (`table` の中身に正規表現文字列がある) ので `utils.percentformat(re.escape(format), table)` がよいかも。

**Comment by kmyk** [comment]
`grep '\<re\>' onlinejudge/**/*.py` として調べるとやらかしてるのはその行のみのようですし、このままプルリクにしてみませんか？

**Comment by Pachicobue** [comment]
了解です。

**Comment by fukatani** [comment]
```python
def glob_with_format(directory: pathlib.Path, format: str) -> List[pathlib.Path]:
    table = {}
    table['s'] = '*'
    table['e'] = '*'
    pattern = str(directory / utils.percentformat(format, table))
    paths = list(map(pathlib.Path, glob.glob(pattern)))
    for path in paths:
        log.debug('testcase globbed: %s', path)
    return paths
```

ところで、ここをみて思ったんですけど、globはどうでしょうね？[abc]みたいなディレクトリはありえるでしょうか。

**Comment by kmyk** [comment]
これも正しい。まったく気付いてなかった。 `*` というディレクトリは作れるし `[` というファイルは存在するのでバグです。

修正は次のようにする方がよさそう。

```python
    pattern = glob.escape(str(directory)) + '/' + utils.percentformat(glob.escape(format), table))
```

(@Pachicobue これもプルリクに入れるかどうかは任せます)

**Comment by kmyk** [comment]
(@Pachicobue 申し訳ないですがPyPIへの反映はしばらく待ってください。これに関するテストの追加とコードフォーマッタの導入を一緒にやってからバージョンを上げたいので)
