### ISSUE TITLE
Travis CI failed to deply v0.1.53

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#285]
```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests_toolbelt/_compat.py", line 56, in <module>
    from requests.packages.urllib3.contrib.pyopenssl \
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
ModuleNotFoundError: No module named 'OpenSSL'
```

https://travis-ci.org/kmyk/online-judge-tools/jobs/486079655#L2877-L2882

**Comment by kmyk** [comment]
`https://github.com/requests/toolbelt/pull/242`
`altendky commented 35 minutes ago` なのでちょうどさっき発生したバグらしい 待ちましょう
