### ISSUE TITLE
Runtime error on Python 3.5.2

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#363]
Python3.5.2 で実行したんですが、以下のようなエラーで、動作しないです。
（最近online-judge-toolsアップデートしてなかった。）
```
Traceback (most recent call last):
  File "/home/ryo/workspace/github/chainer-wind-env/bin/oj", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ryo/workspace/github/online-judge-tools/oj", line 4, in <module>
    import onlinejudge._implementation.main
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/__init__.py", line 3, in <module>
    import onlinejudge.service
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/service/__init__.py", line 2, in <module>
    import onlinejudge.service.anarchygolf
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/service/anarchygolf.py", line 14, in <module>
    import onlinejudge._implementation.testcase_zipper
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/_implementation/testcase_zipper.py", line 9, in <module>
    import onlinejudge._implementation.format_utils
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/_implementation/format_utils.py", line 11, in <module>
    import onlinejudge._implementation.utils as utils
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/_implementation/utils.py", line 215, in <module>
    def getter_with_load_details(name: str, type: Union[str, Type]) -> Callable:
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

def getter_with_load_details(name: str, type: Union[str, Type]) -> Callable:の型アノテーション止めると動作します。(Unionの方)

**Comment by fukatani** [comment]
Union[str, Any]にすると動作するようになります。Typeがよくない？

**Comment by kmyk** [comment]
`Type` でなくて `type` にするのが適切な可能性があります。
https://docs.python.org/3/library/typing.html#typing.Type

**Comment by kmyk** [comment]
ところでこれなぜCI上で再現しなかったのだろう？

**Comment by fukatani** [comment]
たしかにtypeだと動きます。

**Comment by fukatani** [comment]
Type[***]のように引数取らないといけないってことですかね。

**Comment by kmyk** [comment]
そのようですね。

しかしドキュメントには 3.5 の段階で次のようにもあるので、本来は現状でも動くはずです。

> Type[Any] is equivalent to Type which in turn is equivalent to type, which is the root of Python’s metaclass hierarchy.

**Comment by kmyk** [comment]
「Python 3.5 をサポート」と言っている以上は 3.5.x すべてで動いてほしいので、CIは 3.5.0 での動作を確認するのがよさそう？

**Comment by fukatani** [comment]
あまりそこまでやっているリポジトリを見かけませんが、kmykさんがそうしたいなら私はOKです。
あるいは我々Python3.5.2ユーザーにアップデートを迫ってもらってもかまいません。

**Comment by kmyk** [comment]
とりあえず 3.5.0 を指定する形でプルリクを出しました
