### ISSUE TITLE
Sometimes raised AttributeError, when offline.

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#410]
発生条件：
Ubuntu16.04でネットに繋いで一度Atcoderにsubmit、その後パソコンをスリープして、タリーズコーヒーでブラッドオレンジジュースを頼み、店内のwifiをコネクト先に選択した後でネットワーク使用条件に同意する前に再submitする、みたいなムーブをした時に何回か見ました。
よくわかりません。

まあselectがNoneかチェック入れればいいのかもしれません。
```
[x] load cookie from: /home/ryo/.local/share/online-judge-tools/cookie.jar
[x] GET: http://yahoo-procon2018-qual.contest.atcoder.jp/submit
[x] 200 OK
Traceback (most recent call last):
  File "/home/ryo/.virtualenvs/default/bin/oj", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ryo/work/github/online-judge-tools/oj", line 7, in <module>
    onlinejudge.implementation.main.main(args=sys.argv[1:])
  File "/home/ryo/work/github/online-judge-tools/onlinejudge/implementation/main.py", line 314, in main
    run_program(namespace, parser=parser)
  File "/home/ryo/work/github/online-judge-tools/onlinejudge/implementation/main.py", line 287, in run_program
    submit(args)
  File "/home/ryo/work/github/online-judge-tools/onlinejudge/implementation/command/submit.py", line 69, in submit
    langs = problem.get_language_dict(session=sess)
  File "/home/ryo/work/github/online-judge-tools/onlinejudge/service/atcoder.py", line 239, in get_language_dict
    for option in select.find_all('option'):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by kmyk** [comment]
@fukatani このエラーメッセージはバージョンがいくつのときのものですか？

**Comment by kmyk** [comment]
6.0.0 以降は AtCoder とは HTTPS で通信するはずなので、このような中間者攻撃によるエラーは `requests.HTTPError` などのネットワークのエラーとして報告されるはずです。次にタリーズへ行ったときに確認してみてください

**Comment by fukatani** [comment]
ありがとうございます！1.6.0を使っていました。
コラボレーターなのにわかっていなかった :smiling_imp: 勉強になります。
アップデートして使ってみて、またなにか起きたら報告します。
