### ISSUE TITLE
the score of problem may be surrounded by \( \)

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#411]
落ち

https://atcoder.jp/contests/wupc2019/tasks/wupc2019_a

**Comment by kmyk** [comment]
`<p>配点 : \(100\) 点</p>` などと `\(` `\)` で囲まれてるのが原因。同様のものはこのコンテストだけ

``` console
$ oj dl -n https://atcoder.jp/contests/wupc2019/tasks/wupc2019_a
[x] problem recognized: AtCoderProblem.from_url('https://atcoder.jp/contests/wupc2019/tasks/wupc2019_a'): https://atcoder.jp/contests/wupc2019/tasks/wupc2019_a
[x] load cookie from: /home/user/.local/share/online-judge-tools/cookie.jar
[x] GET: https://atcoder.jp/contests/wupc2019/tasks/wupc2019_a
[x] 200 OK
Traceback (most recent call last):
  File "/home/user/.local/bin/oj", line 7, in <module>
    onlinejudge._implementation.main.main(args=sys.argv[1:])
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge/_implementation/main.py", line 279, in main
    run_program(namespace, parser=parser)
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge/_implementation/main.py", line 252, in run_program
    download(args)
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge/_implementation/command/download.py", line 52, in download
    samples = problem.download_sample_cases(session=sess)  # type: ignore
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge/service/atcoder.py", line 550, in download_sample_cases
    return self.download_content(session=session).sample_cases
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge/service/atcoder.py", line 543, in download_content
    self._cached_content = _AtCoderProblemContent_from_html(resp.content.decode(resp.encoding), problem=self)
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge/service/atcoder.py", line 507, in _AtCoderProblemContent_from_html
    score = _AtCoderProblemContent_parse_score(soup)
  File "/home/user/.local/lib/python3.6/site-packages/onlinejudge/service/atcoder.py", line 490, in _AtCoderProblemContent_parse_score
    return int(utils.remove_suffix(utils.remove_prefix(p.text, '配点 : '), ' 点'))
ValueError: invalid literal for int() with base 10: '\\(100\\)'
```
