### ISSUE TITLE
memory limits may be not an integer

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#412]
落ちる

https://atcoder.jp/contests/dwacon2018-final-open/tasks

**Comment by kmyk** [comment]
``` python
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onlinejudge
>>> onlinejudge.service.atcoder.AtCoderContest.from_url('https://atcoder.jp/contests/dwacon2018-final-open').list_problems()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/GitHub/online-judge-tools/onlinejudge/service/atcoder.py", line 287, in list_problems
    return [AtCoderProblem._from_table_row(tr) for tr in tbody.find_all('tr')]
  File "/home/user/GitHub/online-judge-tools/onlinejudge/service/atcoder.py", line 287, in <listcomp>
    return [AtCoderProblem._from_table_row(tr) for tr in tbody.find_all('tr')]
  File "/home/user/GitHub/online-judge-tools/onlinejudge/service/atcoder.py", line 529, in _from_table_row
    return _AtCoderProblemContentPartial_from_row(tr).problem
  File "/home/user/GitHub/online-judge-tools/onlinejudge/service/atcoder.py", line 365, in _AtCoderProblemContentPartial_from_row
    memory_limit_byte = int(utils.remove_suffix(tds[3].text, ' MB')) * 1000 * 1000  # TODO: confirm this is MB truly, not MiB
ValueError: invalid literal for int() with base 10: '252.525'
```
