### ISSUE TITLE
Dispatch API raises assertion error?

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#578]
Some classes `raises` AssertionError if parse is not succeeded.
But should we always return `None` when URL is invalid? Since such inputs are possible in user applications.
```python
>>> dispatch.problem_from_url("https://yukicoder.me/contests/241/")  # Assert raises
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/dispatch.py", line 53, in problem_from_url
    problem = cls.from_url(url)
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/service/yukicoder.py", line 359, in from_url
    return cls()
  File "/home/ryo/workspace/github/online-judge-tools/onlinejudge/service/yukicoder.py", line 238, in __init__
    assert problem_no or problem_id
AssertionError
>>> dispatch.problem_from_url("https://yahoo.co.jp")  # return None

```

**Comment by fukatani** [comment]
I found another failure pattern

```python
problem_from_url("https://atcoder.jp/contests/abc143/submissions/8059148")
```

raises `Exception`.

**Comment by kmyk** [comment]
I checked it, and it seems just a bug.

https://github.com/kmyk/online-judge-tools/blob/74f7237f650700de2f57c72773b23c339d2f3808/onlinejudge/service/yukicoder.py#L359

**Comment by fukatani** [comment]
Ah, OK!
I will fix it!
