### ISSUE TITLE
pip install . に失敗する

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#75]
https://travis-ci.org/kmyk/online-judge-tools/builds/288689200

``` python
$ pip install .
Processing /home/travis/build/kmyk/online-judge-tools
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-eiiyuaru-build/setup.py", line 3, in <module>
        from onlinejudge.implementation.version import __author__, __email__, __license__, __url__, __version__
      File "/tmp/pip-eiiyuaru-build/onlinejudge/__init__.py", line 3, in <module>
        import onlinejudge.atcoder
      File "/tmp/pip-eiiyuaru-build/onlinejudge/atcoder.py", line 5, in <module>
        import onlinejudge.dispatch
      File "/tmp/pip-eiiyuaru-build/onlinejudge/dispatch.py", line 2, in <module>
        import onlinejudge.implementation.logging as log
      File "/tmp/pip-eiiyuaru-build/onlinejudge/implementation/logging.py", line 12, in <module>
        import colorama
    ImportError: No module named 'colorama'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-eiiyuaru-build/
```

**Comment by kmyk** [comment]
`import onlinejudge.implementation.version` は `import onlinejudge` も暗に含んでしまうらしいのが原因ぽい 気付かなかった

**Comment by kmyk** [comment]
気付くの遅れた対策としては develop -> master のpull requestsだけ対象にすればよいですね
